[versions]
accompanist = "0.31.0"
androidGradlePlugin = "8.3.0"
androidxActivity = "1.7.2"
androidxAppCompat = "1.6.1"
androidxComposeBom = "2023.05.01"
androidxComposeCompiler = "1.5.0"
androidxComposeCompilerPlugin = "1.5.0"
androidxComposeFoundation = "1.5.0"
androidxComposeFoundationLayout = "1.5.0"
androidxComposeIconsExtended = "1.5.0"
androidxComposeLifecycle = "2.6.1"
androidxComposeMaterial = "1.5.0"
androidxComposeMaterial3 = "1.5.0"
androidxComposeMaterialIconsExtended = "1.5.0"
androidxComposeMaterialWindow = "1.0.1"
androidxComposeNavigation = "2.5.3"
androidxComposeRuntime = "1.5.0"
androidxComposeRuntimeLivedata = "1.5.0"
androidxComposeRuntimeRxjava2 = "1.5.0"
androidxComposeRuntimeRxjava3 = "1.5.0"
androidxComposeRuntimeSaveable = "1.5.0"
androidxComposeUi = "1.5.0"
androidxComposeUiGraphics = "1.5.0"
androidxComposeUiTest = "1.5.0"
androidxComposeUiTestJunit4 = "1.5.0"
androidxComposeUiTestManifest = "1.5.0"
androidxComposeUiTooling = "1.5.0"
androidxComposeUiToolingPreview = "1.5.0"
androidxCore = "1.10.1"
androidxCoreSplashscreen = "1.0.1"
androidxDataStore = "1.0.0"
androidxEspresso = "3.5.1"
androidxHiltNavigationCompose = "1.1.0-alpha01"
androidxLifecycle = "2.6.1"
androidxLifecycleRuntimeCompose = "2.6.1"
androidxLifecycleRuntimeKtx = "2.6.1"
androidxLifecycleViewModelCompose = "2.6.1"
androidxLifecycleViewModelKtx = "2.6.1"
androidxNavigation = "2.5.3"
androidxRoom = "2.5.1"
androidxTest = "1.5.0"
androidxTestExt = "1.1.5"
androidxTestRules = "1.5.0"
androidxTestRunner = "1.5.2"
androidxTracing = "1.1.0"
androidxUiAutomator = "2.2.0"
androidxWindowManager = "1.0.0"
coil = "2.4.0"
hilt = "2.51.1"
hiltExt = "1.0.0"
junit4 = "4.13.2"
kermit = "2.0.0-RC2"
koin = "3.5.6"
koinAndroidCompose = "3.5.6"
koinAndroidxCompose = "3.5.6"
koinAndroidxWorkManager = "3.4.0"
koinCore = "3.5.6"
koinKtor = "3.3.1"
koinTest = "3.5.6"
koinTestJunit4 = "3.4.0"
koinTestJunit5 = "3.4.0"
kotlin = "2.2.0"
kotlinxCoroutines = "1.8.1"
kotlinxDatetime = "0.5.0"
kotlinxSerializationJson = "1.6.0"
ktorClientAndroid = "2.0.0"
ktorClientContentNegotiation = "2.0.0"
ktorClientCore = "2.0.0"
ktorClientLogging = "2.0.0"
ktorClientMock = "2.0.0"
ktorClientNegotiation = "2.0.0"
ktorClientOkHttp = "2.0.0"
ktorClientSerialization = "2.0.0"
ktorClientSerializationJson = "2.0.0"
ktorClientSerializationKotlinxJson = "2.0.0"
ktorClientSerializationProtobuf = "2.0.0"
ktorClientSerializationXml = "2.0.0"
ktorServerAuth = "2.0.0"
ktorServerAuthJwt = "2.0.0"
ktorServerContentNegotiation = "2.0.0"
ktorServerCore = "2.0.0"
ktorServerCors = "2.0.0"
ktorServerHostCommon = "2.0.0"
ktorServerNetty = "2.0.0"
ktorServerSerialization = "2.0.0"
ktorServerSerializationJson = "2.0.0"
ktorServerSerializationKotlinxJson = "2.0.0"
ktorServerSerializationProtobuf = "2.0.0"
ktorServerSerializationXml = "2.0.0"
ktorServerSessionAuth = "2.0.0"
ktorServerSessions = "2.0.0"
ktorServerTestHost = "2.0.0"
mockk = "1.13.5"
multiplatformSettings = "1.1.1"
napier = "2.6.1"
protobufJava = "3.23.2"
protobufJavaUtil = "3.23.2"
protobufKotlin = "3.23.2"
protobufKotlinLite = "3.23.2"
robolectric = "4.9.2"
skie = "0.10.4"
sqlDelightAndroidDriver = "1.5.5"
sqlDelightBom = "1.5.5"
sqlDelightCoroutinesExtensions = "1.5.5"
sqlDelightDriver = "1.5.5"
sqlDelightJdbcDriver = "1.5.5"
sqlDelightNativeDriver = "1.5.5"
sqlDelightRuntimeJdk = "1.5.5"
sqlDelightSqliteDriver = "1.5.5"
turbine = "0.13.0"
