# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'CocktailCraft' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocktailCraft
  pod 'shared', :path => '../shared'
  
  # Additional iOS dependencies
  pod 'Kingfisher', '~> 7.0'  # For image loading

  # Debug tools (only in debug builds)
  pod 'DebugSwift', :git => 'https://github.com/DebugSwift/DebugSwift.git', :tag => '1.7.13.1', :configurations => ['Debug']

  # Unit tests import the shared framework directly; search paths come from
  # the host app target. (UI tests only drive the app, so they need no pods.)
  target 'CocktailCraftTests' do
    inherit! :search_paths
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable all preview-related settings
      config.build_settings['ENABLE_PREVIEWS'] = 'NO'
      config.build_settings['SWIFT_EMIT_LOC_STRINGS'] = 'NO'
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'

      # Fix Swift 6 concurrency issues for DebugSwift
      if target.name == 'DebugSwift'
        config.build_settings['SWIFT_STRICT_CONCURRENCY'] = 'minimal'
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end