# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'CocktailCraft' do
  # Pods for CocktailCraft
  
  # KMM Framework
  pod 'shared', :path => '../shared'
  
  # UI & Image Loading
  pod 'Kingfisher', '~> 7.0'
  
  # Dependency Injection
  pod 'Factory', '~> 2.1'
  
  # Development Tools
  pod 'SwiftLint', '~> 0.52'
  pod 'R.swift', '~> 7.0'
  
  # Keychain Access
  pod 'KeychainSwift', '~> 20.0'
  
  target 'CocktailCraftTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ViewInspector', '~> 0.9'
    pod 'SnapshotTesting', '~> 1.9'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end